### ISSUE TITLE
关于博文流程的一些问题与建议

### ISSUE THREAD

**Issue by leeenx** [o2team/o2team.github.io#10]
1. hexo 安装的说明，应该分 window 和 mac。
现在线上的是 window 的安装方式，mac 要加 su 才能顺利安装。我最开始就是复制粘贴发现安装后跑不通，后来重新走一次流程跑通的。

2. 官网博文的分享
做为标榜玩转微信手Q平台的团队，博文居然没有做分享优化！这是个需要严正对待的事情。分享时居然拿全文最大的那张图片做为分享图标，也没有对应的分享文案。建议在 md 头部新建几个字段来存放：分享标题，分享描述，分享icon。如下：
shahreIcon: //misc.aotu.io/leeenx/cover-logo.jpg
shareTitle: 分享标题
shareDesc: 分享描述

3. 官网的 markdown 转换样式不全面。
像 代码高亮\<code\> , 斜体\<em\> 这两个标识就没有对应的样式。

建议多搜集一下使用者的意见，将博文流程完善起来，让后来者不困惑。

**Comment by mamboer** [comment]
感谢老李的反馈，
1. mac是否要su是看你当前账户是否有管理者权限的，这点可以加入到Readme提示下
2. 博文分享的处理和代码高亮已让av根据

**Comment by booxood** [comment]
博文分享针对微信增加了配置项
```
wechat:
    share_cover: http://misc.aotu.io/leeenx/cover-logo.jpg
    share_title: CSS3 Mask 安利报告 
    share_desc: 朋友，你听说过 CSS3 Mask 这个属性吗？
```
